#!/usr/bin/env bash
# eggs/naked-image.sh — produce a naked base image from a stage3 rootfs
#
# A naked base image is a minimal live ISO built with `eggs produce --naked`:
# kernel + initramfs + base system + penguins-eggs, no desktop environment.
#
# This is the starting point for:
#   - Custom distro builds (add packages, then `eggs produce`)
#   - Recovery images (penguins-recovery integration)
#   - OTA base images (penguins-over-the-air integration)
#
# Variables available: DISTRO RELEASE ARCH ROOTFS OUTPUT_DIR

set -euo pipefail

OUTPUT_DIR="${OUTPUT_DIR:-$(pwd)}"
NAKED_NAME="${DISTRO}-${RELEASE}-${ARCH}-naked"

info() { echo "[naked-image] $*"; }
die()  { echo "[naked-image] ERROR: $*" >&2; exit 1; }

# ── Verify eggs is installed ──────────────────────────────────────────────────
verify_eggs() {
  chroot "${ROOTFS}" which eggs &>/dev/null || \
    die "penguins-eggs not found in rootfs — run install-eggs.sh first"
  info "eggs version: $(chroot "${ROOTFS}" eggs --version 2>/dev/null || echo unknown)"
}

# ── Set hostname and basic identity ──────────────────────────────────────────
configure_identity() {
  info "Configuring base identity"
  echo "${NAKED_NAME}" > "${ROOTFS}/etc/hostname"

  # eggs needs a user to produce from
  if ! chroot "${ROOTFS}" id eggs-user &>/dev/null; then
    chroot "${ROOTFS}" useradd -m -s /bin/bash eggs-user 2>/dev/null || true
    echo "eggs-user:eggs" | chroot "${ROOTFS}" chpasswd 2>/dev/null || true
    echo "eggs-user ALL=(ALL) NOPASSWD: ALL" \
      > "${ROOTFS}/etc/sudoers.d/eggs-user"
  fi
}

# ── Write eggs configuration ──────────────────────────────────────────────────
write_eggs_config() {
  info "Writing eggs configuration"
  mkdir -p "${ROOTFS}/etc/penguins-eggs.d"

  cat > "${ROOTFS}/etc/penguins-eggs.d/eggs.yaml" << YAML
# penguins-eggs configuration — generated by penguins-eggs-stage3
name: ${NAKED_NAME}
fullname: "${DISTRO^} ${RELEASE} ${ARCH} Naked Base"
version: "$(date +%Y.%m.%d)"
user_opt: eggs-user
snapshot_dir: /home/eggs
snapshot_prefix: ${DISTRO}-${RELEASE}-${ARCH}
snapshot_excludes: /etc/penguins-eggs.d/exclude.list
compression: zstd
YAML

  # Standard exclusion list
  cat > "${ROOTFS}/etc/penguins-eggs.d/exclude.list" << 'EXCLUDES'
/home/*/.cache
/home/*/.local/share/Trash
/root/.cache
/tmp/*
/var/cache/apt/archives/*.deb
/var/log/*.log
/var/log/**/*.log
EXCLUDES
}

# ── Produce the naked ISO ─────────────────────────────────────────────────────
produce_naked() {
  info "Running eggs produce --naked"

  # eggs produce needs /proc /sys /dev mounted
  mount -t proc  none     "${ROOTFS}/proc"
  mount --bind   /sys     "${ROOTFS}/sys"
  mount --bind   /dev     "${ROOTFS}/dev"
  mount --bind   /dev/pts "${ROOTFS}/dev/pts"

  local iso_dir="${ROOTFS}/home/eggs"
  mkdir -p "$iso_dir"

  chroot "${ROOTFS}" bash -c "
    eggs produce --naked --nointeractive --prefix ${DISTRO}-${RELEASE}-${ARCH} 2>&1
  " || {
    info "eggs produce failed — ISO may be incomplete"
    # Unmount and continue — don't fail the whole build
  }

  # Unmount
  umount -l "${ROOTFS}/dev/pts" 2>/dev/null || true
  umount -l "${ROOTFS}/dev"     2>/dev/null || true
  umount -l "${ROOTFS}/sys"     2>/dev/null || true
  umount -l "${ROOTFS}/proc"    2>/dev/null || true

  # Copy ISO out
  local iso
  iso=$(find "$iso_dir" -name "*.iso" | head -1)
  if [[ -n "$iso" ]]; then
    cp "$iso" "${OUTPUT_DIR}/"
    sha256sum "${OUTPUT_DIR}/$(basename "$iso")" \
      > "${OUTPUT_DIR}/$(basename "$iso").sha256"
    info "Naked ISO: $(basename "$iso")"
  else
    info "No ISO produced — eggs produce may need a running system"
    info "Stage3 tarball is still usable as a base for manual builds"
  fi
}

# ── Main ──────────────────────────────────────────────────────────────────────
verify_eggs
configure_identity
write_eggs_config
produce_naked

info "Naked image build complete"
